apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc-configs2
  namespace: dev-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jstrahle/gitops-demo-developer.git
    targetRevision: main
    path: demoapp1
  destination:
    server: https://kubernetes.default.svc   # the local cluster
    namespace: openshift-gitops              # fallback ns for namespaced resources
  syncPolicy:
    automated:
      prune: true        # delete resources removed from Git
      selfHeal: true     # revert manual drift back to Git state
