apiVersion: v1
kind: Service
metadata:
  name: brahe-ssh
  namespace: virtual-machines
spec:
  type: NodePort
  selector:
    vm.kubevirt.io/name: myvm
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022
